name: "HA Energy Optimizer"
description: "Test"
version: "0.2.0"
slug: "ha_energy_optimizer"
url: "https://github.com/LudoThijssen/ha-energy-optimizer"
arch:
  - aarch64
  - amd64
  - armv7
init: false
map:
  - data
log_level: info
